version 5.3.5

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,6 @@
-# Anticonf (tm) script by Jeroen Ooms (2022)
+#!/bin/sh
+
+# Anticonf (tm) script by Pacha (2024)
 # This script will query 'pkg-config' for the required cflags and ldflags.
 # If pkg-config is unavailable or does not find the library, try setting
 # INCLUDE_DIR and LIB_DIR manually via e.g:
@@ -8,9 +10,8 @@
 PKG_CONFIG_NAME="tesseract"
 PKG_DEB_NAME="libtesseract-dev libleptonica-dev"
 PKG_RPM_NAME="tesseract-devel leptonica-devel"
-PKG_BREW_NAME="tesseract"
-PKG_TEST_HEADER="<baseapi.h>"
-PKG_CFLAGS="-I/usr/include/tesseract -I/usr/include/leptonica"
+PKG_BREW_NAME="tesseract leptonica"
+PKG_CFLAGS="-I/usr/include/leptonica"
 PKG_LIBS="-ltesseract"
 
 # Use pkg-config if available
@@ -19,6 +20,7 @@ if [ $? -eq 0 ]; then
   PKGCONFIG_CFLAGS=`pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME}`
   PKGCONFIG_LIBS=`pkg-config --libs ${PKG_CONFIG_NAME}`
 fi
+
 # Note that cflags may be empty in case of success
 if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   echo "Found INCLUDE_DIR and/or LIB_DIR!"
@@ -26,23 +28,32 @@ if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   PKG_LIBS="-L$LIB_DIR $PKG_LIBS"
 elif [ "$PKGCONFIG_CFLAGS" ] || [ "$PKGCONFIG_LIBS" ]; then
   echo "Found pkg-config cflags and libs!"
-  PKG_CFLAGS=${PKGCONFIG_CFLAGS}
-  PKG_LIBS=${PKGCONFIG_LIBS}
-elif [ `uname` = "Darwin" ]; then
-  test ! "$CI" && brew --version 2>/dev/null
-  if [ $? -eq 0 ]; then
-    BREWDIR=`brew --prefix`
-    PKG_CFLAGS="-I$BREWDIR/include/tesseract -I$BREWDIR/include/leptonica"
-    PKG_LIBS="-L$BREWDIR/lib $PKG_LIBS"
-  else
-    curl -sfL "https://autobrew.github.io/scripts/tesseract" > autobrew
-    . ./autobrew
-  fi
+  PKG_CFLAGS="${PKGCONFIG_CFLAGS}"
+  PKG_LIBS="${PKGCONFIG_LIBS}"
+else
+  echo "--------------------------- [ANTICONF] --------------------------------"
+  echo "Configuration failed to find system libraries. Try installing:"
+  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
+  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
+  echo " * brew: $PKG_BREW_NAME (Mac OSX)"
+  echo "If the libraries are already installed, check that 'pkg-config' is in your"
+  echo "PATH and PKG_CONFIG_PATH contains the necessary .pc files. If pkg-config"
+  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
+  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
+  echo "-------------------------- [ERROR MESSAGE] ---------------------------"
+  exit 1
 fi
 
-# For debugging
-echo "Using PKG_CFLAGS=$PKG_CFLAGS"
-echo "Using PKG_LIBS=$PKG_LIBS"
+# Print debug information
+echo "PKG_CFLAGS: $PKG_CFLAGS"
+echo "PKG_LIBS: $PKG_LIBS"
+
+# Check if the compiler is clang
+if [ "$CC" = "clang" ] || [ "$CXX" = "clang++" ]; then
+  CXX=clang++ -stdlib=libstdc++
+  CXXFLAGS += -stdlib=libstdc++
+  LDFLAGS += -stdlib=libstdc++
+fi
 
 # Tesseract 4 enforces C++11 in the headers but R does not have CXX11CPP
 CPPFLAGS=`${R_HOME}/bin/R CMD config CPPFLAGS`
@@ -54,25 +65,25 @@ else
 CXX11CPP=`${R_HOME}/bin/R CMD config CXXCPP`
 fi
 
-# Test configuration
-echo "Using CXX11CPP: ${CXX11CPP}"
-${CXX11CPP} ${CPPFLAGS} ${PKG_CFLAGS} tools/test.cpp >/dev/null 2>configure.log
+# Create a temporary C++ file to test the compatibility with Tesseract
+cat <<EOF > conftest.cpp
+#include <tesseract/baseapi.h>
+#include <allheaders.h>
+int main() {
+    tesseract::TessBaseAPI api;
+    return 0;
+}
+EOF
 
-# Customize the error
-if [ $? -ne 0 ]; then
-  echo "--------------------------- [ANTICONF] --------------------------------"
-  echo "Configuration failed to find '$PKG_CONFIG_NAME' system library. Try installing:"
-  echo " * deb: $PKG_DEB_NAME (Debian, Ubuntu, etc)"
-  echo " * rpm: $PKG_RPM_NAME (Fedora, CentOS, RHEL)"
-  echo " * brew: $PKG_BREW_NAME (Mac OSX)"
-  echo "If $PKG_CONFIG_NAME is already installed, check that 'pkg-config' is in your"
-  echo "PATH and PKG_CONFIG_PATH contains a $PKG_CONFIG_NAME.pc file. If pkg-config"
-  echo "is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:"
-  echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "-------------------------- [ERROR MESSAGE] ---------------------------"
-  cat configure.log
-  echo "--------------------------------------------------------------------"
-  exit 1
+# Test Tesseract
+# Tesseract enforces C++11
+if ! ${CXX11} -std=gnu++11 -c conftest.cpp -o conftest.o ${PKG_CFLAGS}
+then
+    echo "Tesseract requires C++11 support"
+    rm -rf conftest.cpp conftest.o
+    exit 1
+else
+    rm -rf conftest.cpp conftest.o
 fi
 
 # Write to Makevars
